name: build jpeg-recompress
on:
  workflow_dispatch
permissions: 
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:jpeg-recompress"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/asc8277/jpeg-recompress
          provenance: false